quarkus.http.port=8084

# Base URL for the free currency API (jsdelivr CDN)
currency.base-url=https://cdn.jsdelivr.net

# REST Client configuration
quarkus.rest-client.currency.url=${currency.base-url}