# Base configuration
quarkus.http.port=8083
alphavantage.base-url=https://www.alphavantage.co

# Takes the key from the environment, leaves empty if not set (triggers fallback in code)
alphavantage.api-key=${ALPHAVANTAGE_API_KEY:}

# REST Client Configuration
quarkus.rest-client.alphavantage.url=${alphavantage.base-url}

# --- DEBUGGING & MISC ---

# Allows tracking of URLs called by the REST client in the background
quarkus.log.category."io.quarkus.rest.client".level=DEBUG

# Prevents Quarkus from complaining about missing Bean Validation
quarkus.arc.unremovable-types=de.dhbw.mosbach.stock.AlphaVantageClient

# Activate Swagger UI in production mode (Docker)
quarkus.swagger-ui.always-include=true