quarkus.http.port=8080

# Internal service URLs (Docker compose uses service names)
subscription-service.url=http://subscription-service:8081
alert-service.url=http://alert-service:8082
stock-service.url=http://stock-service:8083
currency-service.url=http://currency-service:8084

# Timer for automatic monitoring (every 10 seconds)
#monitor.cron=0 */1 * * * ? //every minute
monitor.cron=0/10 * * * * ?

# Input validation
validation.query.max-length=50
validation.query.pattern=^[A-Za-z0-9 ]+$

# REST Client configs
quarkus.rest-client.subscription.url=${subscription-service.url}
quarkus.rest-client.alert.url=${alert-service.url}
quarkus.rest-client.stock.url=${stock-service.url}
quarkus.rest-client.currency.url=${currency-service.url}

# --- CORS configuration for the Vue frontend ---
quarkus.http.cors=true
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.origins=/(.*)/